# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iZrE-Xnc0Tl-QX60uEQQOql9YQ6XSjP-
"""

import streamlit as st
import matplotlib.pyplot as plt
import math
import numpy as np
import pandas as pd

st.text("aaa")
