# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iZrE-Xnc0Tl-QX60uEQQOql9YQ6XSjP-
"""

import streamlit as st
import numpy as np
import pandas as pd
import folium
from folium.plugins import Draw
from streamlit_folium import st_folium


data = {
    'x': np.random.random(20),
    'y': np.random.random(20) - 0.5,
    'z': np.random.random(20) - 1.0,
    }
df = pd.DataFrame(data)

st.dataframe(df)
st.table(df)

button_value_A = st.button('Push me!', key=1)

button_value_B = st.button('Push me!', key='second')

flgCheck_A = st.checkbox('Checkbox A')
flgCheck_B = st.checkbox('Checkbox B')

# チェックボックスのイベントは並列して発生する可能性があるため、
# elif を使用すろとイベントのキャッチ漏れに繋がる。
if flgCheck_A:
    st.text('Checkbox A has checked')
if flgCheck_B:
    st.text('Checkbox B has checked')

selected_item = st.radio(
        'which Animal do you like?',
        ['Dog', 'Cat']
    )

st.text(selected_item)

selected_item = st.selectbox('Select item', ['A', 'B', 'C'])

st.text(selected_item)

# デフォルト値を設定する場合は index オプションを設定する。
selected_item = st.selectbox('Select item', ['A', 'B', 'C'], index=1)

# 初期値が 1 なので B が表示される。
st.text(selected_item)

age = st.slider(label='Your Age', min_value=0, max_value=130, value=20)
st.text(age)
# ２つの値を指定し、レンジを取得する。戻り値は２つの値を持つタプル型
age = st.slider(label='Your Age', min_value=0, max_value=130, value=(20, 30))
st.text(age)

inputText_A = st.text_input('Input any words')

# 初期値を指定することも可能
inputText_B = st.text_input(label='Please input text', value='aaa')

# テキストエリアも使い方は同様
inputArea = st.text_area('Please input any strings', 'Place holder')



m = folium.Map(location=[39.949610, -75.150282], zoom_start=5)

# 描画プラグインを有効化
Draw(export=True).add_to(m)

# 地図データの描画
st_data = st_folium(m, width=700, height=500)

# 現在の状態を出力
st.write(st_data)