# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iZrE-Xnc0Tl-QX60uEQQOql9YQ6XSjP-
"""

import streamlit as st

st.title("🔢 足し算アプリ")
a = st.number_input("1つ目の数", value=0)
b = st.number_input("2つ目の数", value=0.0)
if st.button("計算"):
    st.success(f"結果: {a} + {b} = {a + b}")
